@host=https://localhost:7064
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJIb21lS2l0Y2hlbi5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJ3YWxpZCIsImZhbWlseV9uYW1lIjoiSm9obiIsImp0aSI6ImI3YjY5YzcwLTc3NGEtNDZjNi04M2E5LTNhNmQyODY5ODFiYyIsImV4cCI6MTcxNjg1OTM0NSwiaXNzIjoiQnViYmVyRGlubmVyIiwiYXVkIjoiQnViYmVyRGlubmVyIn0.ELuOcS7KV9cbk70SOwwh91dTJcDwj1KekBTDLTabd2o
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}