@host=https://localhost:7064
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5M2U4ZDFiZS02ZjhhLTQ5YzAtYjJjNi01ODM2ZWE4NGI2YzUiLCJnaXZlbl9uYW1lIjoid2FsaWQiLCJmYW1pbHlfbmFtZSI6IkpvaG4iLCJqdGkiOiJlOWJlOTI4Zi1kMGVkLTQ5OTktYTVmNi1iYTRkYThjOTMzNDQiLCJleHAiOjE3MTIwMDk3MzAsImlzcyI6IkJ1YmJlckRpbm5lciIsImF1ZCI6IkJ1YmJlckRpbm5lciJ9.aMsSL71fqqZBVpkK00EGdhHudn9eprw6xINnHjbHutE

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}