@host=https://localhost:7064

POST {{host}}/auth/register
Content-Type: application/json
 
 {
    "firstName":"Xavier",
    "lastName":"John",
    "email":"someone@somewhere.com",
    "password":"Amiko1232!"
}